# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'product/images')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('RRP', models.FloatField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'large')], default='sm', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('b', 'Bundle'), ('v', 'Value')], default='b', max_length=1)),
                ('created', models.DateTimeField(verbose_name='Date created')),
                ('expires', models.DateTimeField(verbose_name='Date expires')),
                ('params', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('colour', models.CharField(default='000000', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Item')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='item',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='product.Promotion'),
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item'),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Image'),
        ),
    ]
