# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='params',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('bn', 'Bundle'), ('rd', 'Reduction'), ('mb', 'Multi-buy'), ('pc', 'Percentage')], default='bd', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='colour',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
