# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160828_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='RRP',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[product.models.validate_non_zero]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[product.models.validate_non_zero]),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='sm', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, validators=[product.models.validate_non_zero]),
        ),
    ]
