# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='promotion',
        ),
        migrations.AddField(
            model_name='item',
            name='promotion',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items_promoted', to='shopping.Promotion'),
        ),
    ]
