# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20160807_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='promotion',
        ),
        migrations.AddField(
            model_name='item',
            name='promotion',
            field=models.ManyToManyField(blank=True, related_name='items_promoted', to='shopping.Promotion'),
        ),
    ]
