# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20160807_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='RRP',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
